### ISSUE TITLE
euXFEL example

### ISSUE THREAD

**Issue by ZhangxiJesseFeng** [lanl/MILK#39]
The issue occurs in cake2MAUD. I am attaching the input files that match the way we did CHESS, APS, and SLAC-MEC. The input calibration files match those on your computer. [euXFEL-HED.zip](https://github.com/lanl/MILK/files/11672123/euXFEL-HED.zip). A local copy of the milk_integrate_local.py and the original milk-integrate-mg.py are included. 

The specific issue originates from this part in the current version of the script:
``` python
def load_interpolation(fname):
        with open(fname, 'rb') as f:
            shape_stored = pickle.load(f)
            radial_stored = pickle.load(f)
            print(pickle.load(f))
            azimuthal_stored = pickle.load(f)
            X_bin = pickle.load(f)
            Y_bin = pickle.load(f)
        return X_bin, Y_bin, shape_stored, radial_stored, azimuthal_stored
```

The original milk-integrate-mg.py runs successfully but the current version returns error:

```
Traceback (most recent call last):
  File "C:\Users\jesse\.conda\envs\rietveld\Scripts\milk-integrate-script.py", line 33, in <module>
    sys.exit(load_entry_point('MILK', 'console_scripts', 'milk-integrate')())
  File "d:\1lanlwork\2023lanl\milk\bin\milk_integrate.py", line 79, in entry_point
    main(files=args.FILE, json_file=args.json, output=args.output,
  File "d:\1lanlwork\2023lanl\milk\bin\milk_integrate.py", line 761, in main
    integrate(detectors, output, overwrite, formats,
  File "d:\1lanlwork\2023lanl\milk\bin\milk_integrate.py", line 602, in integrate
    integration2d(mask, mg, data, opts, stem, formats, histogram_plot)
  File "d:\1lanlwork\2023lanl\milk\bin\milk_integrate.py", line 675, in integration2d
    intensity_det, X_bin_det, Y_bin_det, sigmas_det = cake2MAUD(
  File "d:\1lanlwork\2023lanl\milk\bin\milk_integrate.py", line 304, in cake2MAUD
    X_bin, Y_bin = get_interpolation(
  File "d:\1lanlwork\2023lanl\milk\bin\milk_integrate.py", line 284, in get_interpolation
    X_bin, Y_bin, shape_stored, radial_stored, azimuthal_stored = load_interpolation(
  File "d:\1lanlwork\2023lanl\milk\bin\milk_integrate.py", line 276, in load_interpolation
    azimuthal_stored = pickle.load(f)
EOFError: Ran out of input
```

I see that the two scripts have different cake2MAUD implementations. But I am having difficulty understanding why the input files created following the same procedure I did for the other detector examples won't work with the current version of milk-integrate.

**Comment by djm87** [comment]
Try deleting the pickled object and rerun.

**Comment by ZhangxiJesseFeng** [comment]
I thought it will regenerate if the bins don't match. But now I realize that it will only regenerate if it does not exist. It is good now.
